# Generated by Django 3.2.9 on 2021-11-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='image', upload_to='testimonials/'),
        ),
    ]
